### ISSUE TITLE
Include script in package and make a vignette

### ISSUE THREAD

**Issue by lgatto** [HegemanLab/ProteinTurnover#1]
It would be great for traceability to add the _ProteinTurnover R [script](http://pubs.acs.org/doi/suppl/10.1021/acs.jproteome.5b00772/suppl_file/pr5b00772_si_002.txt) annotated with instruction_ that comes with your manuscript to the package, for example in `/insct/scripts`. 

It would be even better of you could convert it into a reproducible vignette, even if that means using reducing the data size to compile it in a reasonable time.

**Comment by AaronRendahl** [comment]
Version 1.1.1 now includes the script in both .R format and a vignette format. The data to reproduce the vignette is not in the package but (for now, anyway) is available on an external web site.
